name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"   # roda todo dia à meia-noite (UTC)
  workflow_dispatch:       # botão "Run workflow" manual
  push:
    branches: ["main"]     # também roda quando você comitar na main

permissions:
  contents: write          # garante permissão de escrita no repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake (SVG)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: felipemoulin
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Deploy to 'output' branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
