name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"   # 1x por dia
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # necessário para publicar no branch output
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: felipemoulinn
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Deploy to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
